# Generated by Django 4.0.3 on 2022-03-27 07:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumb',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
