# Generated by Django 4.0.3 on 2022-03-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0002_alter_album_thumb_alter_client_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
