# Generated by Django 4.0.3 on 2022-03-27 10:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0003_alter_case_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
